---
kind: pipeline
name: default
steps:
  - name : lint
    image: python:3
    commands:
      - pip install poetry
      - poetry install --only dev
      - poetry run black --check .
      - poetry run flake8 active_boxes
      - poetry run mypy --ignore-missing-imports active_boxes

  - name: test
    image: python:3
    commands:
      - pip install poetry
      - poetry install
      - poetry run pytest -vv --cov=active_boxes
      - codecov
---
kind: signature
hmac: 1a911726b099fc76fc3ea1181f5c7b0c0e4d8d4b1b314204def5da7f21fb299b

...
